language: ruby
before_install: nvm install --lts
rbenv:
- 2.5.3
addons:
  postgresql: 9.6
script:
- bundle exec rails db:{create,migrate} RAILS_ENV=test
- bundle exec rspec
deploy:
  provider: heroku
  app: damp-fjord-30128
  run: rails db:migrate

env:
  global:
#     api_key: qqzx1qe44GpQOAFwQRBNDm/H7sWkp6YI2TOSZt5PSl6JTNZD/dmGe1A4OM9YXwsggLEqCBBWKspWVj9Umh42tF7nKu4TSAcVPfWe0ZhN3PzJbpDDdk0pViVOn9xUDZnEYCzuLJmMJdXE1YeTQEifHX5n1s5Y7AeFaVHTt54r2aVkF0wxRsUE6bf0B+XVltd2Ww+39U/pfz2LDpPQq3niT4fT06mLOjy7zmFMW28QiL5Ig9muULaefe6MfpHTW/aidy1xfJ7sV9j8eMiLMba0Fm6B4rkIdq18h3aX4IlnfgcDni1cIOj9HOpbqRgNENjfYEO6pTgDdqUkL01Has3EmD8TbWDfGWOUUaDtz4XKKkpgDYkprutU8fjzqXRPJNMLc02J3/6B0l7zBp9ZEt6U94bwYA10NT8HCA4ScdOQ+Q8lwJaQSQH9j6ih52sncj0AbvZkRXwVlKKSh0VjES/gk2v+zulxQqb0UsLYHifUIPnxYRqag3wnCE8l5BlgxYuQLiTI7AC4Yane/5Jb238rgDQW7avcJYFWBYiFWl240XHIH3s8nTOcmqNYSv/Z1JANvQIAOYnuINsqoiA1RHIdCGZ0jnXWNAGZ2U2nqyQlu15HbC34uVd5HowMmgnTDn+AfkHuymQCK9YBPUDdYHbWuXMGqKwTFlJMNQKaXaYo7L0=
    movie_details: "123"
