language: ruby
rbenv:
- 2.5.3
addons:
  postgresql: 9.6
script:
- bundle exec rails db:{create,migrate} RAILS_ENV=test
- bundle exec rspec
language: node_js
node_js:
- node
deploy:
  provider: heroku
  api_key:
  app: damp-fjord-30128
  run: rails db:migrate
