language: ruby
before_install: nvm install --lts
rbenv:
- 2.5.3
addons:
  postgresql: 9.6
script:
- bundle exec rails db:{create,migrate} RAILS_ENV=test
- bundle exec rspec
deploy:
  provider: heroku
  app: damp-fjord-30128
  run: rails db:migrate
  api_key:
    secure: rym2bv2y4bGvuok4yEYKRUoLBijRbGVHxd+1o7+Qnv1JgyfSqVxAdgqWpaE2edUO/4gMXesPwnS2Ux7OshzdzB5UHVwmIwzJFQHsC7fjSxDPxzvXu/WsolYpdp8eSNZC5rh72ar/LEihSeoBHHJizh3x+dK8gWeY27y+zeeA7TwFy9XVD/LyyJoZy5Oxv7MQjhLdnssyaUftV4uAbwYdedI+3Vc+OyhFj55En/kNukeKD9xd1s0xRhDrueQAt/wl8wRkr9+KwhJr8bymdJ7LBnwpxdlXjjm3ITuZGjvjhGxbsx3gO2aBnThBtBGdYQkaHLpbCr5jungz6ww4RSAUcYk+Z8QxrNLDKaq1VPQd7VzQaDniF89m8pELr9G4X2aKYdcxavqd7xdNMstv9uRGiJoaqv/pwFQdre/eV2Flpio9HVlJKm+9h8cIwwTatmXEDs0prMLnHr5SedXm9XPjeF6ol5zf/kCT6jsuXfKbaM23pDoGgJTNcTrLTRtJu+85ny0gMcVpLAjLUJ5BUEy0gal83T2VaKPbYKvFB6u9PXGleJJVektjT+iQ7T9FmoFQgGNpDOwphzHPK4oXdbzvvACYVN9/k4pvwzeHgZrpbVUvqTocsM2vxVZxRoAG56iio45SkRLggsOjcn8EjK7+wypLknUK67eLbnWlFltR3dY=
env:
  global:
    movie_details: '123'